parameters:
- name: dryRun
  type: boolean
  default: true
- name: environmentObj
  displayName: deployment env
  type: object
- name: appDeployConfig
  displayName: Details to deploy the app
  type: object
  default: null
- name: workingDirectory
  type: string
- name: serviceName
  type: string
- name: PSHelperDirectory
  type: string
- name: AppConfigModuleDirectory
  type: string
- name: Version
  type: string
- name: FullBuild
  type: boolean
  default: false
- name: configFileType
  type: string
  default: 'json'
steps:
  - checkout: Self
    path: s/ 
  - checkout: PipelineCommon
    path: s/ADO-Pipeline-Common
    
  - ${{ if ne(parameters.appDeployConfig, '') }}:          
    - pwsh: |
        $PSVersionTable
        sudo apt-get install -y powershell=7.4.0-1.deb --allow-downgrades
      errorActionPreference: silentlyContinue
      displayName: 'Upgrade PowerShell Version'  
    - task: PowerShell@2
      displayName: 'Pepare Import App Config Files'
      inputs:
        targetType: filePath
        filePath: '$(Pipeline.Workspace)/s/ADO-Pipeline-Common/templates/powershell/build/ValidateAndMergeConfigFile.ps1'
        arguments: > 
         -SchemaFilePath '$(Pipeline.Workspace)/s/ADO-Pipeline-Common/templates/config/schema.${{ parameters.configFileType }}'
         -CommonConfigFilePath '${{ parameters.appDeployConfig.filepath }}/appConfig.${{ parameters.configFileType }}'
         -ConfigFilePath '${{ parameters.appDeployConfig.filepath }}/appConfig.${{ parameters.environmentObj.name }}.${{ parameters.configFileType }}'
         -AppConfigModuleDirectory ${{ parameters.AppConfigModuleDirectory }}
        failOnStderr: true
        pwsh: true
        workingDirectory: '$(Pipeline.Workspace)/s'
    - task: replacetokens@5
      displayName: 'Replace tokens in App Config Files'
      inputs:
        tokenPattern: doublebraces
        inlineVariables: |
          keyvaultName: ${{ parameters.environmentObj.appKeyVault }}
          serviceName: ${{ parameters.serviceName }}
          env: ${{ parameters.environmentObj.name }}
          keyVaultContentType: "application/vnd.microsoft.appconfig.keyvaultref+json;charset=utf-8"
          resourceid: 'uri":"https://${{ parameters.environmentObj.appKeyVault }}.vault.azure.net/secrets'
        targetFiles: |
          ${{ parameters.workingDirectory }}/${{ parameters.appDeployConfig.filepath }}/appConfig.${{ parameters.environmentObj.name }}.${{ parameters.configFileType }}
    - task: AzureCLI@2
      displayName: 'Import App Config'
      inputs:
        azureSubscription: '${{ parameters.environmentObj.serviceConnection}}'
        scriptType: pscore
        scriptLocation: scriptPath
        scriptPath: '$(Pipeline.Workspace)/s/ADO-Pipeline-Common/templates/powershell/build/ImportAppConfig.ps1'
        arguments: > 
          -AppConfig '${{ parameters.environmentObj.appConfiguration }}' 
          -ServiceName '${{ parameters.serviceName }}' 
          -ConfigFilePath '${{ parameters.appDeployConfig.filepath }}/appConfig.${{ parameters.environmentObj.name }}.${{ parameters.configFileType }}'          
          -KeyVault '${{ parameters.environmentObj.appKeyVault }}'
          -PSHelperDirectory ${{ parameters.PSHelperDirectory }} 
          -AppConfigModuleDirectory ${{ parameters.AppConfigModuleDirectory }} 
          -Version ${{ parameters.Version }}
          -BuildId $(Build.BuildId)
          -FullBuild $${{ parameters.FullBuild }}
        addSpnToEnvironment: true          
        failOnStandardError: false
        workingDirectory: '$(Pipeline.Workspace)/s'  
  