parameters:
- name: dryRun
  type: boolean
  default: true
- name: deploymentEnv
  displayName: deployment env
  type: object
- name: appDeployConfig
  displayName: Details to deploy the app
  type: object
  default: null
- name: workingDirectory
  type: string

steps:

  - checkout: Self
    path: s/
  - task: replacetokens@5
    displayName: 'Replace tokens in config'
    inputs:
      tokenPattern: doublebraces
      targetFiles: |
        ${{ parameters.workingDirectory }}/${{ parameters.appDeployConfig.filepath }}/appConfig.${{ parameters.deploymentEnv.name }}.json
  - ${{ if ne(parameters.appDeployConfig, '') }}:
    - task: AzureAppConfigurationPush@6
      displayName: 'Import Azure App Configuration'
      inputs:
        azureSubscription: ${{ parameters.deploymentEnv.serviceConnection }}
        AppConfigurationEndpoint: 'https://${{ parameters.deploymentEnv.appConfiguration }}.azconfig.io'
        ConfigurationFile: '$(Pipeline.Workspace)/s/${{ parameters.appDeployConfig.filepath }}/appConfig.${{ parameters.deploymentEnv.name }}.json'
        FileContentProfile: appconfig/kvset
        DryRun: ${{ parameters.dryRun }}