parameters:
  - name: url
    type: string 
steps:
  - template: /templates/steps/additional-tools.yaml
    parameters:
      DockerCompose : true      
  - template: /templates/steps/tests/performance-test.yaml
    parameters:
      testDir : '$(Pipeline.Workspace)/s/test/performance'
      testOutputDir: '$(Pipeline.Workspace)/s/test-output'
      typeOfTest: 'PostDeploy'
      scriptPath: '$(Pipeline.Workspace)/s/PipelineCommon/templates/scripts/jtl_junit_converter.py'     
      url: ${{ parameters.url }}
  - template: /templates/steps/tests/acceptance-test.yaml
    parameters:
      testDir : '$(Pipeline.Workspace)/s'
      testOutputDir: '$(Pipeline.Workspace)/s/test-output'
      typeOfTest: 'PostDeploy'  
      url: ${{ parameters.url }}
