parameters:
  - name: url
    type: string
  - name: performanceTestEnvs
    type: string
  - name: acceptanceTestEnvs
    type: string
  - name: accessibilityTestEnvs
    type: string        
  - name: envName
    type: string
steps:
  - template: /templates/steps/additional-tools.yaml
    parameters:
      DockerCompose : true
  - ${{ if contains(parameters.performanceTestEnvs, parameters.envName) }}:
    - template: /templates/steps/tests/performance-test.yaml
      parameters:
        testDir : '$(Pipeline.Workspace)/s/test/performance'
        testOutputDir: '$(Pipeline.Workspace)/s/test-output'
        typeOfTest: 'PostDeploy'
        scriptPath: '$(Pipeline.Workspace)/s/ADO-Pipeline-Common/templates/scripts/jtl_junit_converter.py'     
        url: ${{ parameters.url }}
  - ${{ if contains(parameters.acceptanceTestEnvs, parameters.envName) }}:
    - template: /templates/steps/tests/acceptance-test.yaml
      parameters:
        testDir : '$(Pipeline.Workspace)/s'
        testOutputDir: '$(Pipeline.Workspace)/s/test-output'
        typeOfTest: 'PostDeploy'
        url: ${{ parameters.url }}
  - ${{ if contains(parameters.accessibilityTestEnvs, parameters.envName) }}:
    - template: /templates/steps/tests/accessibility-test.yaml
      parameters:
        testDir : '$(Pipeline.Workspace)/s'
        testOutputDir: '$(Pipeline.Workspace)/s/test-output'
        typeOfTest: 'PostDeploy'
        url: ${{ parameters.url }}       
