parameters:
  - name: serviceName
  - name: IsPrBuild
    displayName: Is PR Build
    type: boolean
    default: false   
  - name: appTestConfig
    displayName: AppTestConfig
    type: object
  
steps:
  - task: PowerShell@2
    displayName: Provision any required resources
    inputs:
        targetType: 'inline'
        script: |
          Write-Host "In Progress: Provision any required resources......."
          Write-Host "read ./provision.azure.yaml file and create service bus resources like queue and topic using az cli"
          Write-Host "read ./docker-compose.migrate.yaml file and create pr database using docke compose"

  - task: PowerShell@2
    displayName: 'Provision Resources'
    inputs:
      targetType: filePath
      filePath: '$(Pipeline.Workspace)/s/PipelineCommon/templates/powershell/build/Provision-Resources.ps1'
      arguments: > 
        -InfraChartHomeDir '$(Pipeline.Workspace)/s/helm/${{ parameters.serviceName }}-infra'
        -ServiceName '${{ parameters.serviceName }}'
        -PipelineCommonDirectory '$(Pipeline.Workspace)/s/PipelineCommon'
      failOnStderr: false
      pwsh: true
      workingDirectory: '$(Pipeline.Workspace)/s'   

  - task: PowerShell@2
    displayName: Display System details
    inputs:
      targetType: 'inline'
      script: |
        Write-Host "Build Id = $(Build.BuildId)"    
        Write-Host "Build Number = $(Build.BuildNumber)"      
        Write-Host "Build Reason = $(Build.Reason)"  
        Write-Host "Build SourceBranch = $(Build.SourceBranch)"  
        Write-Host "Build SourceBranchName = $(Build.SourceBranchName)"  
        Write-Host "System PullRequest PullRequestId = $(System.PullRequest.PullRequestId)"  
        Write-Host "System PullRequest PullRequestNumber = $(System.PullRequest.PullRequestNumber)"             

  - task: PowerShell@2
    displayName: Build test image
    inputs:
        targetType: 'inline'
        script: |
          Write-Host "In Progress: Build test image if ./docker-compose.test.yaml file exist"    
          Write-Host "Create powershell module for `Build` related task like 'buildTestImage'"

  - task: PowerShell@2
    displayName: Run tests
    inputs:
        targetType: 'inline'
        script: |
          Write-Host "In Progress: Run tests if ./docker-compose.test.yaml file exist"     
          Write-Host "Create powershell module for `Test` related task like 'runTests'"

  - task: PowerShell@2
    displayName: Run Service Acceptance Tests
    inputs:
        targetType: 'inline'
        script: |
          Write-Host "In Progress: Run Service Acceptance Tests if ./docker-compose.acceptance.yaml file exist"  
          Write-Host "Create powershell module for `Test` related task like 'runServiceAcceptanceTests'"