parameters:
  - name: teamName
  - name: serviceName
  - name: IsPrBuild
    displayName: Is PR Build
    type: boolean
    default: false       
  - name: appTestConfig
    displayName: AppTestConfig
    type: object

steps:
  - template: /templates/steps/additional-tools.yaml
    parameters:
      DockerCompose : true
  - task: AzureCLI@2
    displayName: 'Provision Resources for Tests'
    inputs:
      azureSubscription: ${{ parameters.appTestConfig.preDeployTest.serviceConnection }}
      scriptType: pscore
      scriptLocation: scriptPath
      scriptPath: '$(Pipeline.Workspace)/s/ADO-Pipeline-Common/templates/powershell/test/Provision-Resources.ps1'
      arguments: > 
        -InfraChartHomeDir '$(Pipeline.Workspace)/s/helm/${{ parameters.serviceName }}-infra'
        -PipelineCommonDirectory '$(Pipeline.Workspace)/s/ADO-Pipeline-Common'
        -TeamName '${{ parameters.teamName }}'
        -IsPrBuild '${{ parameters.IsPrBuild }}'
        -Environment '${{ parameters.appTestConfig.preDeployTest.envToTest }}'
        -AzureServiceBusResourceGroup '${{ parameters.appTestConfig.preDeployTest.azureServiceBusResourceGroup }}'
        -AzureServiceBusNamespace '${{ parameters.appTestConfig.preDeployTest.azureServiceBusNamespace }}'
      addSpnToEnvironment: true
      failOnStandardError: false
      workingDirectory: '$(Pipeline.Workspace)/s'  
  - ${{ if or(parameters.IsPrBuild, contains(parameters.appTestConfig.preDeployTest.testsToRun,'integration')) }}:
    - template: /templates/steps/tests/integration-test.yaml
      parameters:
        service : '${{ parameters.serviceName }}'
        testDir : '$(Pipeline.Workspace)/s'
        testOutputDir: '$(Pipeline.Workspace)/s/test-output'
  - ${{ if or(parameters.IsPrBuild, contains(parameters.appTestConfig.preDeployTest.testsToRun,'service-acceptance')) }}:
    - template: /templates/steps/tests/service-acceptance-test.yaml
      parameters:
        service : '${{ parameters.serviceName }}'
        testDir : '$(Pipeline.Workspace)/s'
        testOutputDir: '$(Pipeline.Workspace)/s/test-output' 
  - ${{ if or(parameters.IsPrBuild,contains(parameters.appTestConfig.preDeployTest.testsToRun,'owasp')) }}:
    - template: /templates/steps/tests/owasp-test.yaml
      parameters:
        testDir : '$(Pipeline.Workspace)/s'
        testOutputDir: '$(Pipeline.Workspace)/s/test-output'     
  - ${{ if or(parameters.IsPrBuild,contains(parameters.appTestConfig.preDeployTest.testsToRun,'accessibility')) }}:           
    - template: /templates/steps/tests/accessibility-test.yaml
      parameters:
        testDir : '$(Pipeline.Workspace)/s'
        testOutputDir: '$(Pipeline.Workspace)/s/test-output'
  - ${{ if or(parameters.IsPrBuild,contains(parameters.appTestConfig.preDeployTest.testsToRun,'performance')) }}:        
    - template: /templates/steps/tests/performance-test.yaml
      parameters:
        testDir : '$(Pipeline.Workspace)/s/test/performance'
        testOutputDir: '$(Pipeline.Workspace)/s/test-output'
        scriptPath: '$(Pipeline.Workspace)/s/ADO-Pipeline-Common/templates/scripts/jtl_junit_converter.py'     
  - ${{ if or(parameters.IsPrBuild,contains(parameters.appTestConfig.preDeployTest.testsToRun,'acceptance')) }}:        
    - template: /templates/steps/tests/acceptance-test.yaml
      parameters:
        testDir : '$(Pipeline.Workspace)/s'
        testOutputDir: '$(Pipeline.Workspace)/s/test-output'
  # Need to verify when to delete resources? After Pre deployment or post deployment test?
  - task: AzureCLI@2
    displayName: 'Delete Dynamically provisioned resources'
    condition: always()
    inputs:
      azureSubscription: ${{ parameters.appTestConfig.preDeployTest.serviceConnection }}
      scriptType: pscore
      scriptLocation: scriptPath
      scriptPath: '$(Pipeline.Workspace)/s/ADO-Pipeline-Common/templates/powershell/test/Delete-Resources.ps1'
      arguments: > 
        -PipelineCommonDirectory '$(Pipeline.Workspace)/s/ADO-Pipeline-Common'
        -TeamName '${{ parameters.teamName }}'
        -IsPrBuild '${{ parameters.IsPrBuild }}'
        -Environment '${{ parameters.appTestConfig.preDeployTest.envToTest }}'
        -AzureServiceBusResourceGroup '${{ parameters.appTestConfig.preDeployTest.azureServiceBusResourceGroup }}'
        -AzureServiceBusNamespace '${{ parameters.appTestConfig.preDeployTest.azureServiceBusNamespace }}'
      addSpnToEnvironment: true
      failOnStandardError: false
      workingDirectory: '$(Pipeline.Workspace)/s'           