parameters:
  - name: serviceName
  - name: IsPrBuild
    displayName: Is PR Build
    type: boolean
    default: false   
  - name: appTestConfig
    displayName: AppTestConfig
    type: object
  
steps:
  # - task: PowerShell@2
  #   displayName: Provision any required resources
  #   inputs:
  #       targetType: 'inline'
  #       script: |
  #         Write-Host "In Progress: Provision any required resources......."
  #         Write-Host "read ./provision.azure.yaml file and create service bus resources like queue and topic using az cli"
  #         Write-Host "read ./docker-compose.migrate.yaml file and create pr database using docke compose"

  # - task: PowerShell@2
  #   displayName: 'Provision Resources'
  #   inputs:
  #     targetType: filePath
  #     filePath: '$(Pipeline.Workspace)/s/PipelineCommon/templates/powershell/build/Provision-Resources.ps1'
  #     arguments: > 
  #       -InfraChartHomeDir '$(Pipeline.Workspace)/s/helm/${{ parameters.serviceName }}-infra'
  #       -ServiceName '${{ parameters.serviceName }}'
  #       -PipelineCommonDirectory '$(Pipeline.Workspace)/s/PipelineCommon'
  #       -IsPrBuild '${{ parameters.IsPrBuild }}'
  #       -BuildId $(Build.BuildId)
  #     failOnStderr: false
  #     pwsh: true
  #     workingDirectory: '$(Pipeline.Workspace)/s'   

  - task: AzureCLI@2
    displayName: 'Provision Resources'
    inputs:
      azureSubscription: ${{ parameters.appTestConfig.serviceConnection }}
      scriptType: pscore
      scriptLocation: scriptPath
      scriptPath: '$(Pipeline.Workspace)/s/PipelineCommon/templates/powershell/build/Provision-Resources.ps1'
      arguments: > 
        -InfraChartHomeDir '$(Pipeline.Workspace)/s/helm/${{ parameters.serviceName }}-infra'
        -ServiceName '${{ parameters.serviceName }}'
        -PipelineCommonDirectory '$(Pipeline.Workspace)/s/PipelineCommon'
        -IsPrBuild '${{ parameters.IsPrBuild }}'
        -BuildId $(Build.BuildId)
        -AzureServiceBusResourceGroup '${{ parameters.appTestConfig.azureServiceBusResourceGroup }}'
        -AzureServiceBusNamespace '${{ parameters.appTestConfig.azureServiceBusNamespace }}'
      addSpnToEnvironment: true
      failOnStandardError: false
      workingDirectory: '$(Pipeline.Workspace)/s'    

  - bash: 'env | sort'    
      
  - task: PowerShell@2
    displayName: Build test image
    inputs:
        targetType: 'inline'
        script: |
          Write-Host "In Progress: Build test image if ./docker-compose.test.yaml file exist"    
          Write-Host "Create powershell module for `Build` related task like 'buildTestImage'"

  - task: PowerShell@2
    displayName: Run tests
    inputs:
        targetType: 'inline'
        script: |
          Write-Host "In Progress: Run tests if ./docker-compose.test.yaml file exist"     
          Write-Host "Create powershell module for `Test` related task like 'runTests'"

  - task: PowerShell@2
    displayName: Run Service Acceptance Tests
    inputs:
        targetType: 'inline'
        script: |
          Write-Host "In Progress: Run Service Acceptance Tests if ./docker-compose.acceptance.yaml file exist"  
          Write-Host "Create powershell module for `Test` related task like 'runServiceAcceptanceTests'"