parameters:
  - name: serviceName
  - name: IsPrBuild
    displayName: Is PR Build
    type: boolean
    default: false   
  - name: appTestConfig
    displayName: AppTestConfig
    type: object
  
steps:
  - task: PowerShell@2
    displayName: 'Set Test file variable flags'
    inputs:
      targetType: filePath
      filePath: '$(Pipeline.Workspace)/s/PipelineCommon/templates/powershell/test/Set-TestFileVariables.ps1'
      failOnStderr: false
      pwsh: true
      workingDirectory: '$(Pipeline.Workspace)/s'   

  - task: AzureCLI@2
    displayName: 'Provision Resources for Tests'
    inputs:
      azureSubscription: ${{ parameters.appTestConfig.serviceConnection }}
      scriptType: pscore
      scriptLocation: scriptPath
      scriptPath: '$(Pipeline.Workspace)/s/PipelineCommon/templates/powershell/test/Provision-Resources.ps1'
      arguments: > 
        -InfraChartHomeDir '$(Pipeline.Workspace)/s/helm/${{ parameters.serviceName }}-infra'
        -ServiceName '${{ parameters.serviceName }}'
        -PipelineCommonDirectory '$(Pipeline.Workspace)/s/PipelineCommon'
        -IsPrBuild '${{ parameters.IsPrBuild }}'
        -BuildId $(Build.BuildId)
        -AzureServiceBusResourceGroup '${{ parameters.appTestConfig.azureServiceBusResourceGroup }}'
        -AzureServiceBusNamespace '${{ parameters.appTestConfig.azureServiceBusNamespace }}'
      addSpnToEnvironment: true
      failOnStandardError: false
      workingDirectory: '$(Pipeline.Workspace)/s'    

  - bash: 'env | sort'    
      
  - task: PowerShell@2
    displayName: Build test image
    condition: eq(variables['docker_compose_dot_test_yaml'], 'true')
    inputs:
        targetType: 'inline'
        script: |
          Write-Host "In Progress: Build test image if ./docker-compose.test.yaml file exist"    
          Write-Host "Create powershell module for `Build` related task like 'buildTestImage'"

  - task: PowerShell@2
    displayName: Run tests
    condition: eq(variables['docker_compose_dot_test_yaml'], 'true')
    inputs:
        targetType: 'inline'
        script: |
          Write-Host "In Progress: Run tests if ./docker-compose.test.yaml file exist"     
          Write-Host "Create powershell module for `Test` related task like 'runTests'"

  - task: PowerShell@2
    displayName: Run Service Acceptance Tests
    condition: eq(variables['docker_compose_dot_acceptance_yaml'], 'true')
    inputs:
        targetType: 'inline'
        script: |
          Write-Host "In Progress: Run Service Acceptance Tests if ./docker-compose.acceptance.yaml file exist"  
          Write-Host "Create powershell module for `Test` related task like 'runServiceAcceptanceTests'"