parameters:
  - name: snykConnection
    type: string       
  - name: acrRepoName
    type: string   
  - name: snykOrganizationName
    type: string
  - name: failOnThreshold
    type: string
    default: 'high'
  - name: manifestPath
    type: string
    default: ''         

steps:
- ${{ each projectManifestPath in split(parameters.manifestPath, ';') }}:
  - task: SnykSecurityScan@1
    displayName: 'Snyk Application scan'
    inputs:
      serviceConnectionEndpoint: ${{ parameters.snykConnection }} 
      testDirectory: '$(Build.SourcesDirectory)'
      ${{ if ne(projectManifestPath, '') }}:
        targetFile: '${{ projectManifestPath }}'
      failOnIssues: true
      monitorOnBuild: false
      projectName: '${{ parameters.acrRepoName }}'
      organization: '${{ parameters.snykOrganizationName }}'
      failOnThreshold: '${{ parameters.failOnThreshold }}'
    enabled: true
    continueOnError: ${{ ne(variables['Build.Reason'], 'PullRequest') }}