parameters:
  - name: snykConnection
    type: string       
  - name: acrRepoName
    type: string   
  - name: snykOrganizationName
    type: string
  - name: failOnThreshold
    type: string
    default: 'high'
  - name: manifestPath
    type: string
    default: ''         

steps:
- task: SnykSecurityScan@1
  displayName: 'Snyk Application scan'
  inputs:
    serviceConnectionEndpoint: ${{ parameters.snykConnection }} 
    testDirectory: '$(Build.SourcesDirectory)'
    ${{ if ne(parameters.manifestPath, '') }}:
      targetFile: '${{ parameters.manifestPath }}'
    failOnIssues: ${{ eq(variables['Build.Reason'], 'PullRequest') }}
    monitorOnBuild: false
    projectName: '${{ parameters.acrRepoName }}'
    organization: '${{ parameters.snykOrganizationName }}'
    failOnThreshold: '${{ parameters.failOnThreshold }}'
  enabled: true
  continueOnError: ${{ ne(variables['Build.Reason'], 'PullRequest') }}