description: App Config Schema
type: array
items:
  type: object
  required:
  - key
  - value
  properties:
    key:
      type: string
    value:
      type: string
    type:
      type: string
      enum: [
        "keyvault"
      ]