pr:
  branches:
    include:
      - main

trigger:
  batch: true
  branches:
    include:
      - "main"

resources:
  repositories:
    - repository: DEFRA-ADPPipelineCommon
      name: DEFRA/adp-pipeline-common
      endpoint: DEFRA
      type: github
      ref: refs/tags/1.0.0-latest

extends:
  template: pipelines/common-tag-and-release.yaml@DEFRA-ADPPipelineCommon
