name: ${{ parameters.buildNumber }}-${{ parameters.appKeyVault }}-${{ Build.variableGroups }}

parameters:
- name: buildNumber
  type: string  
- name: secretNames
  type: string  
- name: variableGroups
  type: string  
- name: serviceConnection
  type: string
- name: appKeyVault
  type: string    
- name: privateAgentName
  type: string   

trigger:
- none

resources:
  repositories:
    - repository: ADOPipelineCommon
      name: DEFRA/ADO-Pipeline-Common
      endpoint: DEFRA
      type: github
      ref: refs/heads/rv/323021-importvariables

variables:
- ${{ each varGroup in split(parameters.variableGroups, ';') }}:
  - group: '${{ varGroup }}'
- name: PSHelperDirectory
  value: '$(Pipeline.Workspace)/s/ADO-Pipeline-Common/templates/powershell/modules/ps-helpers'
  
stages:
- stage: ImportSecrets
  pool: ${{ parameters.privateAgentName }}  
  jobs:
  - job: Import
    steps:
      - checkout: ADOPipelineCommon
        path: s/ADO-Pipeline-Common
        clean: true
      - ${{ each secret in split(parameters.secretNames, ';') }} :
        - template: ../steps/secrets-import-kv.yaml
          parameters:
            workingDirectory: '$(Pipeline.Workspace)/s'
            PSHelperDirectory: ${{ variables.PSHelperDirectory }}
            secretName: ${{ secret }}
            serviceConnection: ${{ parameters.ServiceConnection }}
            appKeyVault: ${{ parameters.appKeyVault }}  